<h3>Solving Classification Problems Using Scikit Learn</h3>

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

sns.set_style('darkgrid')
plt.rcParams['figure.figsize'] = [10, 6]

In [2]:
churn_df = pd.read_csv('./datasets/customer_churn.csv')
churn_df.head(30)

RowNumber  CustomerId     Surname  CreditScore Geography  Gender  Age  \
0           1    15634602    Hargrave          619    France  Female   42   
1           2    15647311        Hill          608     Spain  Female   41   
2           3    15619304        Onio          502    France  Female   42   
3           4    15701354        Boni          699    France  Female   39   
4           5    15737888    Mitchell          850     Spain  Female   43   
5           6    15574012         Chu          645     Spain    Male   44   
6           7    15592531    Bartlett          822    France    Male   50   
7           8    15656148      Obinna          376   Germany  Female   29   
8           9    15792365          He          501    France    Male   44   
9          10    15592389          H?          684    France    Male   27   
10         11    15767821      Bearce          528    France    Male   31   
11         12    15737173     Andrews          497     Spain    Male   24   
12         13    15632264         Kay          476    France  Female   34   
13         14    15691483        Chin          549    France  Female   25   
14         15    15600882       Scott          635     Spain  Female   35   
15         16    15643966     Goforth          616   Germany    Male   45   
16         17    15737452       Romeo          653   Germany    Male   58   
17         18    15788218   Henderson          549     Spain  Female   24   
18         19    15661507     Muldrow          587     Spain    Male   45   
19         20    15568982         Hao          726    France  Female   24   
20         21    15577657    McDonald          732    France    Male   41   
21         22    15597945    Dellucci          636     Spain  Female   32   
22         23    15699309   Gerasimov          510     Spain  Female   38   
23         24    15725737      Mosman          669    France    Male   46   
24         25    15625047         Yen          846    France  Female   38   
25         26    15738191     Maclean          577    France    Male   25   
26         27    15736816       Young          756   Germany    Male   36   
27         28    15700772     Nebechi          571    France    Male   44   
28         29    15728693  McWilliams          574   Germany  Female   43   
29         30    15656300    Lucciano          411    France    Male   29   

    Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0        2       0.00              1          1               1   
1        1   83807.86              1          0               1   
2        8  159660.80              3          1               0   
3        1       0.00              2          0               0   
4        2  125510.82              1          1               1   
5        8  113755.78              2          1               0   
6        7       0.00              2          1               1   
7        4  115046.74              4          1               0   
8        4  142051.07              2          0               1   
9        2  134603.88              1          1               1   
10       6  102016.72              2          0               0   
11       3       0.00              2          1               0   
12      10       0.00              2          1               0   
13       5       0.00              2          0               0   
14       7       0.00              2          1               1   
15       3  143129.41              2          0               1   
16       1  132602.88              1          1               0   
17       9       0.00              2          1               1   
18       6       0.00              1          0               0   
19       6       0.00              2          1               1   
20       8       0.00              2          1               1   
21       8       0.00              2          1               0   
22       4       0.00              1          1               0   
23      

In [4]:
# Removing unnecessary columns
churn_df = churn_df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

<p>Dividing Data into Features and Labels</p>

In [5]:
# Creating the feature set
x = churn_df.drop(['Exited'], axis=1)

# Creating a label set
y = churn_df['Exited']

In [6]:
x.head(30)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0           619    France  Female   42       2       0.00              1   
1           608     Spain  Female   41       1   83807.86              1   
2           502    France  Female   42       8  159660.80              3   
3           699    France  Female   39       1       0.00              2   
4           850     Spain  Female   43       2  125510.82              1   
5           645     Spain    Male   44       8  113755.78              2   
6           822    France    Male   50       7       0.00              2   
7           376   Germany  Female   29       4  115046.74              4   
8           501    France    Male   44       4  142051.07              2   
9           684    France    Male   27       2  134603.88              1   
10          528    France    Male   31       6  102016.72              2   
11          497     Spain    Male   24       3       0.00              2   
12          476    France  Female   34      10       0.00              2   
13          549    France  Female   25       5       0.00              2   
14          635     Spain  Female   35       7       0.00              2   
15          616   Germany    Male   45       3  143129.41              2   
16          653   Germany    Male   58       1  132602.88              1   
17          549     Spain  Female   24       9       0.00              2   
18          587     Spain    Male   45       6       0.00              1   
19          726    France  Female   24       6       0.00              2   
20          732    France    Male   41       8       0.00              2   
21          636     Spain  Female   32       8       0.00              2   
22          510     Spain  Female   38       4       0.00              1   
23          669    France    Male   46       3       0.00              2   
24          846    France  Female   38       5       0.00              1   
25          577    France    Male   25       3       0.00              2   
26          756   Germany    Male   36       2  136815.64              1   
27          571    France    Male   44       9       0.00              2   
28          574   Germany  Female   43       3  141349.43              1   
29          411    France    Male   29       0   59697.17              2   

    HasCrCard  IsActiveMember  EstimatedSalary  
0           1               1        101348.88  
1           0               1        112542.58  
2           1               0        113931.57  
3           0               0         93826.63  
4           1               1         79084.10  
5           1               0        149756.71  
6           1               1         10062.80  
7           1               0        119346.88  
8           0               1         74940.50  
9           1               1         71725.73  
10          0               0         80181.12  
11          1               0         76390.01  
12          1               0         26260.98  
13          0               0        190857.79  
14          1               1         65951.65  
15          0               1         64327.26  
16          1               0          5097.67  
17          1               1         14406.41  
18          0               0        158684.81  
19          1               1         54724.03  
20          1               1        170886.17  
21          1               0        138555.46  
22          1               0        118913.53  
23          0               1          8487.75  
24          1               1        187616.16  
25          0               1        124508.29  
26          1               1        170041.95  
27          0               0         38433.35  
28          1               1        100187.43  
29          1               1         53483.21

In [7]:
y.head(30)

0     1
1     0
2     1
3     0
4     0
5     1
6     0
7     1
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    1
17    0
18    0
19    0
20    0
21    0
22    1
23    0
24    0
25    0
26    0
27    0
28    0
29    0
Name: Exited, dtype: int64

<p>Converting Categorical Data into Numbers</p>

In [8]:
# Dropping categorical columns
numerical = x.select_dtypes(include=['int64', 'float64'])
numerical.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [9]:
categorical = x.select_dtypes(include=['object'])
categorical.head()

Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
4     Spain  Female

In [11]:
# Converting categorical columns to one hot encoded columns
import pandas as pd

cat_numerical = pd.get_dummies(categorical, drop_first=True, dtype=int)
cat_numerical.head()

Geography_Germany  Geography_Spain  Gender_Male
0                  0                0            0
1                  0                1            0
2                  0                0            0
3                  0                0            0
4                  0                1            0

In [12]:
# Concatenating numerical columns with one hot encoded columns
x = pd.concat([numerical, cat_numerical], axis=1)
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88                  0                0   
1               1        112542.58                  0                1   
2               0        113931.57                  0                0   
3               0         93826.63                  0                0   
4               1         79084.10                  0                1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

<p>Dividing the data into training and test sets</p>

In [13]:
# Dividing data into the training and test sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

<p>Data Scaling and Normalization</p>

In [14]:
# Applying standard scaling to the dataset
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

<h5>Solving Classification Problems</h5>

<p>Logistic Regression</p>

In [15]:
from sklearn.linear_model import LogisticRegression

log_clf = LogisticRegression()

# Training the logistic regression classifier
classifier = log_clf.fit(x_train, y_train)

# Making predictions on the test set
y_pred = classifier.predict(x_test)

In [16]:
# Evaluating the algorithm on the test set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1543   64]
 [ 314   79]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

0.811


<p>KNN Classifier</p>

In [17]:
# Importing KNN classifier from sklearn
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)

# Training the KNN classifier
classifier = knn_clf.fit(x_train, y_train)

# Making Predictions on the test set
y_pred = classifier.predict(x_test)

# Evaluating the algorithm on the test set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1514   93]
 [ 247  146]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90      1607
           1       0.61      0.37      0.46       393

    accuracy                           0.83      2000
   macro avg       0.74      0.66      0.68      2000
weighted avg       0.81      0.83      0.81      2000

0.83


<p>Random Forest Classifier</p>

In [18]:
# Importing random forest classifier from sklearn
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=42, n_estimators=500)

# Training the random forest classifier
classifier = rf_clf.fit(x_train, y_train)

# Making predictions on the test set
y_pred = classifier.predict(x_test)

# Evaluating the algorithm on the test set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.76      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000

[[1548   59]
 [ 208  185]]
0.8665


<p>K-Fold Cross Validation</p>

In [19]:
# Importing cross-validation model from sklearn
from sklearn.model_selection import cross_val_score

# Applying 5 fold cross validation
print(cross_val_score(classifier, x, y, cv=5, scoring='accuracy'))

[0.864  0.8725 0.8625 0.863  0.8625]
